/*
 * 1). Snowflake Setup - Creating Database, Schemas and Warehouse
 */

USE ROLE SYSADMIN;

CREATE DATABASE RETAIL_ANALYTICS;

CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA MART;

CREATE WAREHOUSE RETAIL_WH
WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;


/*
 * 2). Creating File Format and Stage
 */

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='\"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RAW.RETAIL_STAGE
FILE_FORMAT = RAW.CSV_FORMAT;


/*
 * 3). Creating Raw Tables
 */

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.RAW_SALES (
    ORDER_ID STRING,
    ORDER_DATE DATE,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    REGION_ID STRING,
    QUANTITY NUMBER,
    SALES_AMOUNT NUMBER(10,2),
    PROFIT NUMBER(10,2),
    DISCOUNT NUMBER(5,2)
);

CREATE OR REPLACE TABLE RAW.DIM_CUSTOMER (
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    SEGMENT STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING
);

CREATE OR REPLACE TABLE RAW.DIM_PRODUCT (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING,
    BRAND STRING
);

CREATE OR REPLACE TABLE RAW.DIM_REGION (
    REGION_ID STRING,
    REGION_NAME STRING,
    MANAGER STRING
);

CREATE OR REPLACE TABLE RAW.DIM_DATE (
    DATE_KEY STRING,
    FULL_DATE DATE,
    MONTH STRING,
    QUARTER NUMBER,
    YEAR NUMBER
);

--TRUNCATE TABLE RAW.RAW_SALES;
--TRUNCATE TABLE MART.FACT_SALES;


/*
 * 4). Creating Stream for incremental loading and pushing data into Snowflake (raw data without any transformation)
 */

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE RAW.RAW_SALES;

COPY INTO RAW.RAW_SALES
FROM @RAW.RETAIL_STAGE/FACT_SALES.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW.DIM_CUSTOMER
FROM @RAW.RETAIL_STAGE/DIM_CUSTOMER.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT);

COPY INTO RAW.DIM_PRODUCT
FROM @RAW.RETAIL_STAGE/DIM_PRODUCT.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT);

COPY INTO RAW.DIM_REGION
FROM @RAW.RETAIL_STAGE/DIM_REGION.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT);

COPY INTO RAW.DIM_DATE
FROM @RAW.RETAIL_STAGE/DIM_DATE.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT);


/*
 * 5). Creating Tables for Data Mart in Snowflake
 */

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA MART;

CREATE OR REPLACE TABLE MART.FACT_SALES (
    ORDER_ID STRING,
    ORDER_DATE DATE,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    REGION_ID STRING,
    QUANTITY NUMBER,
    SALES_AMOUNT NUMBER(10,2),
    PROFIT NUMBER(10,2),
    DISCOUNT NUMBER(5,2)
);

CREATE TABLE MART.DIM_CUSTOMER AS
SELECT DISTINCT *
FROM RAW.DIM_CUSTOMER;

CREATE TABLE MART.DIM_PRODUCT AS
SELECT DISTINCT *
FROM RAW.DIM_PRODUCT;

CREATE TABLE MART.DIM_REGION AS
SELECT DISTINCT *
FROM RAW.DIM_REGION;

CREATE TABLE MART.DIM_DATE AS
SELECT DISTINCT *
FROM RAW.DIM_DATE;


/*
 * 6). Creating Task for Automated Data Loading
 */

SELECT CURRENT_ROLE();

GRANT EXECUTE TASK
ON ACCOUNT
TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA MART;

CREATE OR REPLACE TASK LOAD_SALES_TASK
WAREHOUSE = RETAIL_WH
SCHEDULE = 'USING CRON 0 6 * * * Asia/Kolkata'
AS
INSERT INTO MART.FACT_SALES (
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    REGION_ID,
    QUANTITY,
    SALES_AMOUNT,
    PROFIT,
    DISCOUNT
)

SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    REGION_ID,
    QUANTITY,
    SALES_AMOUNT,
    PROFIT,
    DISCOUNT
FROM RAW.SALES_STREAM;

ALTER TASK LOAD_SALES_TASK RESUME;


/*
 * 7). Business KPI Queries
 */
 
-- Testing Stream
SELECT 
	Count(*) 
FROM RAW.SALES_STREAM;

-- Monthly Revenue
SELECT
	MONTH(ORDER_DATE) AS MONTH_NO,
	SUM(SALES_AMOUNT) AS TOTAL_REVENUE
FROM 
	MART.FACT_SALES
GROUP BY 
	1
ORDER BY 
	1;

--Top 10 Products
SELECT
	PRODUCT_ID,
	SUM(SALES_AMOUNT) AS SALES
FROM 
	MART.FACT_SALES
GROUP BY 
	PRODUCT_ID
ORDER BY 
	SALES DESC
LIMIT 10;

-- Customer Retention
SELECT
	CUSTOMER_ID,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM 
	MART.FACT_SALES
GROUP BY 
	CUSTOMER_ID;